# Real-world region data for all 28 Indian states + 8 union territories,
# researched via web search (not invented) — used to re-ground KAIRO's fixed
# 10-zone template (Main Hall/VIP Zone/Gate 1-3/Corridor A-B/Transport Hub/
# Hotel A-B) to a real venue, transport hub, airport and hotel in whichever
# state/UT an Administrator selects. Fields explicitly unverifiable by search
# are None rather than guessed — the UI shows "not confirmed" for those.

INDIA_REGIONS = {
    # -- North --
    "Delhi": {"city": "New Delhi", "venue": "Jawaharlal Nehru Stadium", "venue_capacity": None,
              "transport_hub": "New Delhi Railway Station", "airport": "Indira Gandhi International Airport (DEL)",
              "hotel": "Taj Palace, New Delhi"},
    "Punjab": {"city": "Ludhiana", "venue": "Guru Nanak Stadium", "venue_capacity": 30000,
               "transport_hub": "Ludhiana Junction Railway Station", "airport": "Sahnewal Airport (LUH)",
               "hotel": "Radisson Blu Hotel, Ludhiana"},
    "Haryana": {"city": "Gurugram", "venue": "Tau Devi Lal Stadium", "venue_capacity": 12000,
                "transport_hub": "Huda City Centre Metro Station", "airport": "Indira Gandhi International Airport, Delhi (DEL)",
                "hotel": "The Leela Ambience Gurugram Hotel & Residences"},
    "Himachal Pradesh": {"city": "Shimla", "venue": "Annadale Ground", "venue_capacity": None,
                          "transport_hub": "Shimla Railway Station (Kalka–Shimla Railway)", "airport": "Shimla Airport, Jubbarhatti (SLV)",
                          "hotel": "Radisson Hotel Shimla"},
    "Uttarakhand": {"city": "Dehradun", "venue": "Rajiv Gandhi International Cricket Stadium", "venue_capacity": 25000,
                    "transport_hub": "Dehradun Railway Station", "airport": "Jolly Grant Airport (DED)",
                    "hotel": "Lemon Tree, Dehradun"},
    "Chandigarh": {"city": "Chandigarh", "venue": "Maharaja Yadavindra Singh Stadium", "venue_capacity": 38000,
                   "transport_hub": "Chandigarh Railway Station", "airport": "Shaheed Bhagat Singh International Airport (IXC)",
                   "hotel": "JW Marriott Hotel Chandigarh"},

    # -- North-Central --
    "Jammu and Kashmir": {"city": "Srinagar", "venue": "Bakshi Stadium", "venue_capacity": 30000,
                           "transport_hub": "Srinagar Railway Station", "airport": "Srinagar International Airport (SXR)",
                           "hotel": "Four Points by Sheraton Srinagar"},
    "Ladakh": {"city": "Leh", "venue": "NDS Stadium", "venue_capacity": 5000,
               "transport_hub": None, "airport": "Kushok Bakula Rimpochee Airport (IXL)",
               "hotel": "Ladakh International Centre Hotel"},
    "Uttar Pradesh": {"city": "Lucknow", "venue": "Ekana Cricket Stadium", "venue_capacity": 50000,
                      "transport_hub": "Lucknow Charbagh Railway Station", "airport": "Chaudhary Charan Singh International Airport (LKO)",
                      "hotel": "Taj Mahal Lucknow"},
    "Rajasthan": {"city": "Jaipur", "venue": "Sawai Mansingh Stadium", "venue_capacity": 30000,
                  "transport_hub": "Jaipur Junction Railway Station", "airport": "Jaipur International Airport (JAI)",
                  "hotel": "Rambagh Palace, Jaipur"},
    "Madhya Pradesh": {"city": "Bhopal", "venue": "TT Nagar Stadium", "venue_capacity": 20000,
                       "transport_hub": "Rani Kamlapati Railway Station", "airport": "Raja Bhoj Airport (BHO)",
                       "hotel": "Jehan Numa Palace Hotel"},
    "Chhattisgarh": {"city": "Raipur", "venue": "Shaheed Veer Narayan Singh International Cricket Stadium", "venue_capacity": 49000,
                     "transport_hub": "Raipur Junction Railway Station", "airport": "Swami Vivekananda International Airport (RPR)",
                     "hotel": "Courtyard by Marriott Raipur"},

    # -- West --
    # Kept as Navi Mumbai/Panvel (this project's own home turf) rather than
    # Mumbai city proper — D Y Patil Stadium, Palm Beach Road, Panvel Station
    # etc. were independently verified earlier and are more specific than a
    # generic Mumbai landmark set.
    "Maharashtra": {"city": "Navi Mumbai / Panvel", "venue": "D Y Patil Stadium, Nerul", "venue_capacity": 45300,
                    "transport_hub": "Panvel Railway Station", "airport": "Chhatrapati Shivaji Maharaj International Airport (BOM) / Navi Mumbai International Airport (NMIA)",
                    "hotel": "Four Points by Sheraton, Vashi"},
    "Gujarat": {"city": "Ahmedabad", "venue": "Narendra Modi Stadium", "venue_capacity": 132000,
                "transport_hub": "Ahmedabad Junction (Kalupur) Railway Station", "airport": "Sardar Vallabhbhai Patel International Airport (AMD)",
                "hotel": "Hyatt Regency Ahmedabad"},
    "Goa": {"city": "Margao", "venue": "Pandit Jawaharlal Nehru Stadium, Fatorda", "venue_capacity": 19000,
            "transport_hub": "Madgaon Junction Railway Station", "airport": "Goa International Airport, Dabolim (GOI)",
            "hotel": "Taj Exotica Resort & Spa, Benaulim"},
    "Dadra and Nagar Haveli and Daman and Diu": {"city": "Silvassa", "venue": None, "venue_capacity": None,
                                                  "transport_hub": "Vapi Railway Station (nearest)", "airport": "Surat Airport (STV, nearest)",
                                                  "hotel": "Silver Waves Resort & Spa, Daman"},
    "Karnataka": {"city": "Bengaluru", "venue": "M. Chinnaswamy Stadium", "venue_capacity": 40000,
                  "transport_hub": "KSR Bengaluru City Junction", "airport": "Kempegowda International Airport (BLR)",
                  "hotel": "Taj West End, Bengaluru"},
    "Kerala": {"city": "Thiruvananthapuram", "venue": "Greenfield International Stadium", "venue_capacity": 50000,
               "transport_hub": "Thiruvananthapuram Central Railway Station", "airport": "Thiruvananthapuram International Airport (TRV)",
               "hotel": "Vivanta Thiruvananthapuram"},

    # -- South --
    "Tamil Nadu": {"city": "Chennai", "venue": "Jawaharlal Nehru Stadium, Chennai", "venue_capacity": 40000,
                   "transport_hub": "MGR Chennai Central Railway Station", "airport": "Chennai International Airport (MAA)",
                   "hotel": "Taj Coromandel, Chennai"},
    "Andhra Pradesh": {"city": "Visakhapatnam", "venue": "Dr. YSR ACA-VDCA Cricket Stadium", "venue_capacity": 27500,
                       "transport_hub": "Visakhapatnam Junction Railway Station", "airport": "Visakhapatnam International Airport (VTZ)",
                       "hotel": "Novotel Visakhapatnam Varun Beach"},
    "Telangana": {"city": "Hyderabad", "venue": "Rajiv Gandhi International Cricket Stadium, Uppal", "venue_capacity": 55000,
                  "transport_hub": "Secunderabad Junction Railway Station", "airport": "Rajiv Gandhi International Airport (HYD)",
                  "hotel": "Taj Falaknuma Palace, Hyderabad"},
    "Puducherry": {"city": "Puducherry", "venue": "Indira Gandhi Sports Stadium", "venue_capacity": 14348,
                   "transport_hub": "Puducherry Railway Station", "airport": "Puducherry Airport (PNY)",
                   "hotel": "Le Dupleix, Puducherry"},
    "Lakshadweep": {"city": "Kavaratti", "venue": "Lakshadweep Water Sports Club", "venue_capacity": None,
                    "transport_hub": "Kavaratti Jetty", "airport": "Agatti Airport (AGX, on a different island)",
                    "hotel": "Kavaratti Island Beach Resort"},
    "Andaman and Nicobar Islands": {"city": "Port Blair", "venue": "Netaji Stadium", "venue_capacity": None,
                                     "transport_hub": "Haddo Jetty", "airport": "Veer Savarkar International Airport (IXZ)",
                                     "hotel": "Sinclairs Bayview, Port Blair"},

    # -- East --
    "West Bengal": {"city": "Kolkata", "venue": "Eden Gardens", "venue_capacity": 68000,
                    "transport_hub": "Howrah Junction Railway Station", "airport": "Netaji Subhas Chandra Bose International Airport (CCU)",
                    "hotel": "Taj Bengal, Kolkata"},
    "Odisha": {"city": "Bhubaneswar", "venue": "Kalinga Stadium", "venue_capacity": 15000,
               "transport_hub": "Bhubaneswar Railway Station", "airport": "Biju Patnaik International Airport (BBI)",
               "hotel": "Trident Bhubaneswar"},
    "Bihar": {"city": "Patna", "venue": "Moin-ul-Haq Stadium", "venue_capacity": 25000,
              "transport_hub": "Patna Junction Railway Station", "airport": "Jay Prakash Narayan International Airport (PAT)",
              "hotel": "Hotel Maurya, Patna"},
    "Jharkhand": {"city": "Ranchi", "venue": "JSCA International Stadium Complex", "venue_capacity": 40000,
                  "transport_hub": "Ranchi Junction Railway Station", "airport": "Birsa Munda Airport (IXR)",
                  "hotel": "Radisson Blu Hotel Ranchi"},
    "Sikkim": {"city": "Gangtok", "venue": "Paljor Stadium", "venue_capacity": None,
               "transport_hub": "New Jalpaiguri Junction (nearest, ~120 km)", "airport": "Pakyong Airport (PYG)",
               "hotel": "Lemon Tree Hotel, Gangtok"},
    "Assam": {"city": "Guwahati", "venue": "Dr. Bhupen Hazarika Cricket Stadium, Barsapara", "venue_capacity": 46000,
              "transport_hub": "Guwahati Railway Station", "airport": "Lokpriya Gopinath Bordoloi International Airport (GAU)",
              "hotel": "Vivanta Guwahati"},

    # -- Northeast --
    "Meghalaya": {"city": "Shillong", "venue": "Jawaharlal Nehru Stadium, Shillong", "venue_capacity": 15100,
                  "transport_hub": "MTC Bus Station, Police Bazaar", "airport": "Shillong Airport, Umroi (SHL)",
                  "hotel": "Hotel Polo Towers, Shillong"},
    "Manipur": {"city": "Imphal", "venue": "Khuman Lampak Main Stadium", "venue_capacity": 29877,
                "transport_hub": "Imphal ISBT, Khuman Lampak", "airport": "Bir Tikendrajit International Airport (IMF)",
                "hotel": "Classic Grande Imphal"},
    "Mizoram": {"city": "Aizawl", "venue": "Rajiv Gandhi Stadium, Salem Veng", "venue_capacity": 20000,
                "transport_hub": None, "airport": "Lengpui Airport (AJL)",
                "hotel": "Hotel Regency, Zarkawt, Aizawl"},
    "Nagaland": {"city": "Kohima", "venue": "Indira Gandhi Stadium", "venue_capacity": 20000,
                 "transport_hub": "Naga Bazar ISBT, Kohima", "airport": "Dimapur Airport (DMU, ~74 km)",
                 "hotel": "Hotel Japfu, Kohima"},
    "Tripura": {"city": "Agartala", "venue": "Maharaja Bir Bikram Stadium", "venue_capacity": 30000,
                "transport_hub": "Krishnanagar Bus Terminal, Agartala", "airport": "Maharaja Bir Bikram Airport (IXA)",
                "hotel": "Hotel Sonar Tori, Agartala"},
    "Arunachal Pradesh": {"city": "Itanagar", "venue": "Golden Jubilee Stadium, Yupia", "venue_capacity": 15000,
                          "transport_hub": "Naharlagun Railway Station", "airport": "Donyi Polo Airport, Hollongi (HGI)",
                          "hotel": "Hotel Donyi Polo Ashok, Itanagar"},
}

DEFAULT_REGION = "Maharashtra"  # Panvel/Navi Mumbai — the original demo scenario, D Y Patil / Palm Beach Road / Panvel Station
